# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-13 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.SmallIntegerField(choices=[(0, 'Not done'), (1, 'Done')], default=0)),
                ('accomplished_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomplished_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
