# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-15 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20170413_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-modified_on']},
        ),
        migrations.AddField(
            model_name='task',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
